
from breadcrumbs.models import BreadcrumbsWidget
from contentnavigation.models import ContentNavigationWidget
from contextnavigation.models import ContextNavigationWidget
from linearnavigation.models import LinearNavigationWidget
from sitemap.models import SiteMapWidget
from sitesearch.models import SiteSearchWidget
from treenavigation.models import TreeNavigationWidget
from languageselector.models import LanguageSelectorWidget
